# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-10 03:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Morph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_text', models.TextField()),
                ('text', models.TextField()),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learn.Language')),
            ],
        ),
        migrations.CreateModel(
            name='POS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learn.Language')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learn.Language')),
                ('morphs', models.ManyToManyField(to='learn.Morph')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('filename', models.CharField(max_length=40)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learn.Language')),
                ('translations', models.ManyToManyField(to='learn.Sentence')),
            ],
        ),
        migrations.AddField(
            model_name='morph',
            name='pos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learn.POS'),
        ),
        migrations.AddField(
            model_name='morph',
            name='sentences',
            field=models.ManyToManyField(to='learn.Sentence'),
        ),
    ]
