# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-10 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pos',
            name='desc',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pos',
            name='label',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
