# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-11 06:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0002_auto_20170810_1334'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('desc', models.TextField()),
            ],
        ),
    ]
