# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-11 06:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0004_commonword_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='morph',
            name='common',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='learn.CommonWord'),
        ),
    ]
