# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-14 04:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0005_morph_common'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commonword',
            name='language',
        ),
        migrations.RemoveField(
            model_name='morph',
            name='common',
        ),
        migrations.RemoveField(
            model_name='sentence',
            name='filename',
        ),
        migrations.DeleteModel(
            name='CommonWord',
        ),
    ]
